[package]
name = "math-rs"
version = "0.1.0"
edition = "2021"

repository = "https://github.com/Zirconium419122/math-rs/"
licence = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
